### ISSUE TITLE
segfault on Ubuntu 9.10

### ISSUE THREAD

**Issue by ralfebert** [ahoward/open4#1]
/var/lib/gems/1.8/gems/open4-1.0.1/lib/open4.rb:170: [BUG] Segmentation fault
ruby 1.8.7 (2009-06-12 patchlevel 174) [x86_64-linux]

This only happens sometimes and is not really reproducible. Same code is working without a problem for months on OS X.

**Comment by ahoward** [comment]
not a ton of good without a stacktrace ;-)  open up the core file and dump the stack with gdb.

however, this is most likely an issue with the unbuntu build of ruby - it's blowing up on Thread.new !?

**Comment by ralfebert** [comment]
Sorry, I'm not familiar with providing helpful information for such a problem. I googled a bit around, got the core dump and ran "gdb ruby core". Got:

```
Program terminated with signal 6, Aborted.
0  0x00007f18894494b5 in raise () from /lib/libc.so.6
```

Installed libc6-dbg and got:

```
0  0x00007f18894494b5 in *__GI_raise (sig=<value optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
64  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
in ../nptl/sysdeps/unix/sysv/linux/raise.c
```

I guess this is not what we're looking for? What else can I do to find the cause for this problem?

**Comment by ralfebert** [comment]
Not sure if this happens before or after, it seems that the called process crashes itself (I'm calling pygmentize):

```
 Traceback (most recent call last):
   File "/usr/bin/pygmentize", line 3, in <module>
     pygments.cmdline.main()
   File "/usr/lib/pymodules/python2.6/pygments/cmdline.py", line 423, in main
     print >>sys.stderr, '*** Error while highlighting:'
 IOError: [Errno 32] Broken pipe
```

Running ruby with -d also shows an Exception before the crash:

```
Exception `EOFError' at /var/lib/gems/1.8/gems/open4-1.0.1/lib/open4.rb:55 - end of file reached
/var/lib/gems/1.8/gems/open4-1.0.1/lib/open4.rb:170: [BUG] Segmentation fault
ruby 1.8.7 (2009-06-12 patchlevel 174) [x86_64-linux]
```
