### ISSUE TITLE
threads returned by open4::bg sometimes unkillable

### ISSUE THREAD

**Issue by sjuxax** [ahoward/open4#15]
I occasionally get an error like this:

```
script.rb:47:in `kill': wrong argument type Thread (expected Thread) (TypeError)
```

When I attempt to issue a `Thread::kill` on a thread returned from `open4::bg`. It occurs somewhat rarely but not rarely enough to be considered anomalous and is causing real problems.

Here is the invocation:

```
t = open4::bg("ruby script2.rb", 0=>'', 1=>so, 2=>se)
```

I am counting the seconds that this thread is alive and if it exceeds a given number I issue `Thread::kill(t)`. Usually this works fine; occasionally, maybe ~5% of the time, I get the error cited above. I initially suspected that this may happen when `t` exits before the kill is reached, but this does not appear to be the case; the process that was supposed to be indicated by `t` continues to run unchanged.

Users in #ruby have suggested that this is a race condition that represents a bug in Open4.

**Comment by ahoward** [comment]
this sounds fucking hard to debug!  can you stick a pry in there and try to capture some info about what is happening when this happens?

**Comment by sjuxax** [comment]
Sure. I am not too involved in the Ruby scene yet so perhaps you clarify how you'd like me to use pry. It seems that it just allows me to drop to an interactive shell in the middle of script, basically analogous to setting a breakpoint. Once I get dropped to that shell, what information would be most helpful to get? I will definitely try to collect as much info as possible about the state of `t`; do you have any other suggestions?

**Comment by ahoward** [comment]
that's about it.  otherwise try to provide me with steps to reproduce.  without either i'm tied.
