### ISSUE TITLE
does not work on ruby1.9.2

### ISSUE THREAD

**Issue by Hanmac** [ahoward/open4#2]
the catch in getopts does not work

ArgumentError: uncaught throw "opt"
    from /usr/lib/ruby/gems/1.9.1/gems/open4-1.0.1/lib/open4.rb:188:in `throw'
    from /usr/lib/ruby/gems/1.9.1/gems/open4-1.0.1/lib/open4.rb:188:in`block (4 levels) in getopts'
    from /usr/lib/ruby/gems/1.9.1/gems/open4-1.0.1/lib/open4.rb:187:in `each'
    from /usr/lib/ruby/gems/1.9.1/gems/open4-1.0.1/lib/open4.rb:187:in`block (3 levels) in getopts'
    from /usr/lib/ruby/gems/1.9.1/gems/open4-1.0.1/lib/open4.rb:186:in `each'
    from /usr/lib/ruby/gems/1.9.1/gems/open4-1.0.1/lib/open4.rb:186:in`block (2 levels) in getopts'
    from /usr/lib/ruby/gems/1.9.1/gems/open4-1.0.1/lib/open4.rb:185:in `catch'
    from /usr/lib/ruby/gems/1.9.1/gems/open4-1.0.1/lib/open4.rb:185:in`block in getopts'

**Comment by stnoonan** [comment]
Strings are not symbols.  Change to :opt instead of 'opt' for a fix in open4.rb.

**Comment by Hanmac** [comment]
or remove the catch an change the throw into a return works also (see my fork)

**Comment by noahgibbs** [comment]
There's a pull request to fix this.  It works for me.

**Comment by ahoward** [comment]
a:~/git/ahoward/open4 $ rake test >/dev/null; echo $?; ruby -v
0
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin12.5.0]
