### ISSUE TITLE
popen4 leaks FIFO sometimes

### ISSUE THREAD

**Issue by scycheng** [ahoward/open4#6]
I have not been able to write a simple test case that can replicate this but when I have some code in the following form, it will leak FIFO pipes and, sooner or later, the ruby process aborts with an error of too many files open
while true {
    cmd = "rsync -e 'ssh' --partial #{from_fn} #{nodename}:#{to_fn}"
    pid, stdin, stdout, stderr = Open4::popen4( cmd )
    dontcare, status = Process.waitpid2( pid )
}
If I change the above to the block form, it works like this:

cmd = "rsync -e 'ssh' --partial #{from_fn} #{nodename}:#{to_fn}"
status = Open4::popen4( cmd ) {| pid, stdin, stdout, stderr | }

This code is executed in the context of separate threads.

**Comment by ahoward** [comment]
yep, that code deliberately leaks open file handles: outside the scope of the lib.
