### ISSUE TITLE
popen4 hangs for process with much stderr

### ISSUE THREAD

**Issue by kwerle** [ahoward/open4#7]
I'm running a process that spews a ton of stderr.  popen4 is hanging - I guess because some buffer is filling.

OK - after I submit this let's see if I can attach files...

**Comment by kwerle** [comment]
Damn github issue system.

test.rb:

``` ruby
require 'rubygems'
require "open4"
require "stringio"
require "ruby-debug"

Open4::popen4("./muchoutput") do |pid, stdin, stdout, stderr|
  # stdin.puts "echo 42.out"
  # stdin.puts "echo 42.err 1>&2"
  stdin.close

  puts "pid        : #{ pid }"
  puts "stdout     : #{ stdout.read.strip }"
  puts "stderr     : #{ stderr.read.strip }"
end
```

muchoutput (chmod a+x)

``` ruby
#!/usr/bin/ruby

# 40000.times { $stdout << 'x' }
17500.times { $stderr << 'x' } # more than 15K
```

**Comment by kwerle** [comment]
Awesome.  I tried to use the blocks and it still screws it up.

test.rb:
https://gist.github.com/942749
muchoutput (chmod a+x)
https://gist.github.com/942753

**Comment by ahoward** [comment]
100% chance the process you are driving does not flush it's IO.

On Tue, Apr 26, 2011 at 11:48, kwerle
reply@reply.github.com
wrote:

> I'm running a process that spews a ton of stderr.  popen4 is hanging - I guess because some buffer is filling.
> 
> OK - after I submit this let's see if I can attach files...
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ahoward/open4/issues/7

## 

-a

we can never obtain peace in the outer world until we make peace with
ourselves. - h.h. the 14th dalai lama

**Comment by kwerle** [comment]
What is the workaround or solution?  The test files I 'attached' are trivial - if I could get test.rb to work, that'd be swell.

**Comment by ahoward** [comment]
see Open4.spawn for how to handle multiple streams correctly.

  https://gist.github.com/943384

also, for this kind of simple usage i'd suggest using my 'systemu' gem - also on github.

regards.

**Comment by kwerle** [comment]
I'll check out systemu - thanks for the pointer (you might mention it on your readme page; I couldn't believe how hard it was to find a gem that would do out, err, and status).
And thanks for the workaround.
